# Generated by Django 2.1.3 on 2018-12-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodemo', '0002_auto_20181217_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='favorited',
        ),
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='_author_favorites_+', to='djangodemo.Author'),
        ),
    ]
