# Generated by Django 2.1.3 on 2018-12-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodemo', '0003_auto_20181217_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='favorites',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='favorites',
            field=models.ManyToManyField(related_name='author', to='djangodemo.Author'),
        ),
    ]
